---
- name: 'Enable ports in iptables'
  iptables:
    state: '{{ item.state | default(open_ports_default_state) }}'
    comment: '{{ item.comment | default(open_ports_default_comment) }}'
    action:  '{{ item.action | default(open_ports_default_action) }}'
    chain: '{{ item.chain | default(open_ports_default_chain) }}'
    jump: '{{ item.jump | default(open_ports_default_jump) }}'
    source: '{{ item.source | default(open_ports_default_source) }}'
    protocol: '{{ item.protocol | default(open_ports_default_protocol) }}'
    in_interface: '{{ item.interface | default(omit) }}'
    destination_port: '{{ item.port | default(omit) }}'
    # Optional IP set as source filter
    match_set: '{{ item.ipset | default(omit) }}'
    match_set_flags: |-
      {{ item.ipset_flags | default((item.ipset is defined)
       | ternary(open_ports_default_ipset_flags, omit)) }}
  with_items: '{{ open_ports_list | mandatory }}'
  loop_control:
    label:
      port: '{{ item.get("port") | mandatory | string }}'
      protocol: '{{ item.get("protocol", open_ports_default_protocol) }}'
      comment: '{{ item.get("comment", open_ports_default_comment) }}'
  notify:
    - Save iptables rules
