---
- name: 'Enable ports in iptables'
  iptables:
    comment: '{{ item.comment | default(open_ports_default_comment) }}'
    action:  '{{ item.action | default(open_ports_default_action) }}'
    chain: '{{ item.chain | default(open_ports_default_chain) }}'
    jump: '{{ item.jump | default(open_ports_default_jump) }}'
    source: '{{ item.source | default(open_ports_default_source) }}'
    protocol: '{{ item.protocol | default(open_ports_default_protocol) }}'
    in_interface: '{{ item.interface | default(omit) }}'
    destination_port: '{{ item.port | string | mandatory }}'
  with_items: '{{ open_ports_list | mandatory }}'
  loop_control:
    label:
      comment: '{{ item.comment | default(open_ports_default_comment) }}'
      protocol: '{{ item.protocol }}'
      port: '{{ item.port }}'
  notify:
    - Save iptables rules
