---
- name: 'Enable ports in iptables'
  template:
    src:  'rules.nft'
    dest: '/etc/nft.conf.d/services/{{ service.key }}'
    mode: 0644
  with_dict: '{{ open_ports_list | mandatory }}'
  loop_control:
    loop_var: 'service'
    label: '{{ loop_label }}'
  vars:
    loop_label:
      port:     '{{ service.get("port") | string | default("NONE") }}'
      protocol: '{{ service.get("protocol", open_ports_default_protocol) }}'
      comment:  '{{ service.get("comment",  open_ports_default_comment) }}'
  #notify:
  #  - Reload nftables
